name=SX1262
version=1.0.0
author=ab9nq.william@gmail.com
maintainer=ab9nq.william@gmail.com
sentence=A lightweight driver for the Semtech SX1261/SX1262 LoRa transceivers.
paragraph=Provides raw SPI command abstractions, register configuration, and operational state control for SX1262 ICs.
category=Communication
url=https://github.com/tech500/SX1262-Internal
architectures=*
includes=SX1262.h
